default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: accuweather_development

test:
  <<: *default
  database: accuweather_test

production:
  <<: *default
  database: accuweather_production
  username: accuweather
  password: <%= ENV["ACCUWEATHER_DATABASE_PASSWORD"] %>
